feat(primitives): add back From<U256> for FlaggedStorage (#68)
Removed all implicit conversion methods from FlaggedStorage in
https://github.com/SeismicSystems/seismic-alloy-core/pull/63, but
realized while updating seismic-alloy that we need the `From<U256> for
FlaggedStorage` one because of our seismic-trie:
```
error[E0277]: the trait bound `FlaggedStorage: From<Uint<256, 4>>` is not satisfied
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/alloy-genesis-1.1.0/src/lib.rs:272:17
    |
272 | /                 alloy_trie::root::storage_root_unhashed(
273 | |                     storage
274 | |                         .into_iter()
275 | |                         .filter(|(_, value)| !value.is_zero())
276 | |                         .map(|(slot, value)| (slot, U256::from_be_bytes(*value))),
277 | |                 )
    | |_________________^ the trait `From<Uint<256, 4>>` is not implemented for `FlaggedStorage`
    |
    = note: required for `Uint<256, 4>` to implement `Into<FlaggedStorage>`
```

Annoying part is that this code is never even used because we
reimplemented it for FlaggedStorage in seismic-alloy-genesis, but we
still need it to compile since its a transitive dependency.

So forced to re-add this method. Thankfully this direction
(U256->FlaggedStorage) is way less dangerous than the other lossy
direction FlaggedStorage->U256 so think this is fine. Added a TODO
saying that we can remove this method if we ever implement my plan to
get rid of our seismic-trie fork.